using Avalonia;
using Avalonia.Headless;
using Avalonia.Threading;
using Ts.App;
using Ts.App.ViewModels;
using Ts.App.Views;
using Ts.Core.Definition;
using Ts.Core.Recording;
using Ts.Core.Time;
using Ts.TestSender;

namespace Ts.Shots;

/// <summary>
/// Renders the application window to PNG without a display server.
///
/// Two jobs: it produces the screenshots in the README, and it is the check that the layout
/// actually survives real data. A design reviewed only against a handful of invented rows is a
/// design that has not been reviewed — so the shots are taken with a full definition and a capture
/// generated by the test transmitter, at the density an operator would really see.
/// </summary>
internal static class Program
{
    public static int Main(string[] args)
    {
        var outputDirectory = args.Length > 0 ? args[0] : "docs/screenshots";
        Directory.CreateDirectory(outputDirectory);

        var definitionPath = args.Length > 1 ? args[1] : "samples/vehicle-telemetry.yaml";

        AppBuilder.Configure<Ts.App.App>()
            .UseHeadless(new AvaloniaHeadlessPlatformOptions { UseHeadlessDrawing = false })
            .UseSkia()
            .WithInterFont()
            .SetupWithoutStarting();

        var capture = BuildCapture(definitionPath);

        try
        {
            Shoot(Path.Combine(outputDirectory, "01-scope.png"), 1440, 900, model =>
            {
                model.LoadRecording(capture);
                model.SelectedChannel = model.Channels.FirstOrDefault(c => c.Name == "Motor temp");
            });

            // A few traces at a wider window, with the channel that leaves its declared range
            // selected — the case the range highlight exists for.
            Shoot(Path.Combine(outputDirectory, "02-range-violation.png"), 1440, 900, model =>
            {
                model.LoadRecording(capture);
                model.SelectedChannel = model.Channels.FirstOrDefault(c => c.Name == "Loop current");
                model.TimeWindowIndex = 2;

                foreach (var channel in model.Channels)
                {
                    channel.IsTraceVisible = channel.Name is "Loop current" or "Battery" or "Airspeed";
                }
            });

            Shoot(Path.Combine(outputDirectory, "03-empty.png"), 1280, 820, _ => { });
        }
        finally
        {
            File.Delete(capture.Path);
        }

        Console.WriteLine($"screenshots written to {Path.GetFullPath(outputDirectory)}");
        return 0;
    }

    private static void Shoot(string path, int width, int height, Action<MainWindowViewModel> arrange)
    {
        var window = new MainWindow
        {
            Width = width,
            Height = height,
        };

        window.Show();

        if (window.DataContext is MainWindowViewModel model)
        {
            arrange(model);
        }

        // Let bindings settle and the renderer produce a frame before it is captured.
        for (var i = 0; i < 8; i++)
        {
            Dispatcher.UIThread.RunJobs();
        }

        var frame = window.CaptureRenderedFrame()
            ?? throw new InvalidOperationException("The renderer produced no frame.");

        using var stream = File.Create(path);
        frame.Save(stream);

        window.Close();
        Console.WriteLine($"  {path} ({width}x{height})");
    }

    /// <summary>
    /// A capture generated on the spot rather than committed to the repository: the screenshots
    /// then show what the current decoder really does with the current definition.
    /// </summary>
    private static TsrFile BuildCapture(string definitionPath)
    {
        var set = ChannelSetReader.ReadFile(definitionPath);
        var generator = new SignalGenerator(set);
        var path = Path.Combine(Path.GetTempPath(), $"noktra-shots-{Environment.ProcessId}.tsr");

        using (var writer = TsrWriter.Create(path, set, SystemClock.UnixNowMicros))
        {
            const int rate = 200;
            for (var i = 0; i < rate * 40; i++)
            {
                var time = (long)i * (1_000_000 / rate);
                writer.Write(time, generator.Next(time));
            }
        }

        return TsrReader.ReadFile(path);
    }
}
