<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Ts.Shots</RootNamespace>
    <AssemblyName>Ts.Shots</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="11.1.4" />
    <PackageReference Include="Avalonia.Skia" Version="11.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Ts.App/Ts.App.csproj" />
    <ProjectReference Include="../Ts.TestSender/Ts.TestSender.csproj" />
  </ItemGroup>

</Project>
