using System.Globalization;
using Ts.Core.Definition;

namespace Ts.Core.Tests;

/// <summary>
/// Shared inputs for the golden vector suite.
///
/// Everything here is generated by code. No captured sample file is committed: a test that reads a
/// blob nobody can re-derive proves the blob, not the decoder.
/// </summary>
internal static class Vectors
{
    /// <summary>
    /// The frozen length-field vector: headerLen 2, lenOffset 1, size 1, adjust 2.
    /// A5 03 11 22 33 is therefore exactly one frame.
    /// </summary>
    public const string LengthFieldYaml = """
        name: Length-field vector
        framing:
          mode: lengthField
          headerLength: 2
          lengthOffset: 1
          lengthSize: 1
          adjust: 2
        channels:
          - name: Payload
            offset: 2
            type: u8
        """;

    public static byte[] Bytes(params int[] values)
    {
        var result = new byte[values.Length];
        for (var i = 0; i < values.Length; i++)
        {
            result[i] = checked((byte)values[i]);
        }

        return result;
    }

    public static byte[] Hex(string hex)
    {
        var tokens = hex.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var result = new byte[tokens.Length];
        for (var i = 0; i < tokens.Length; i++)
        {
            result[i] = byte.Parse(tokens[i], NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        }

        return result;
    }

    /// <summary>A single-channel set, so a decode vector reads as one assertion.</summary>
    public static ChannelSet Single(ChannelDef channel) => new()
    {
        Name = "vector",
        Framing = new FramingDef { Mode = FramingMode.Fixed, FrameLength = 64 },
        Channels = new[] { channel },
    };
}
